### ISSUE TITLE
TypeError: lnrpc_1.default is not a function

### ISSUE THREAD

**Issue by mvanderh** [RadarTech/lnrpc#18]
`import createLnRpc from "@radar/lnrpc"` doesn't seem to work. `createLnRpc` isn't a function.

Platform: darwin_x64
Node: v11.10.1
@radar/lnrpc version: 0.5.2-beta

**Comment by cavanmflynn** [comment]
Thanks for opening an issue!

It seems that our typings are using `export default`, rather than `export`, which prevents Typescript from displaying the correct error message and breaks `as *` imports. I'll push a fix ASAP to address this issue. Regardless, you must set `"esModuleInterop": true` in your tsconfig.json if you would like to use a default export.

**Comment by mvanderh** [comment]
Ah excellent, that works. Thanks!

**Comment by cavanmflynn** [comment]
The typings have been fixed in release `0.5.2-beta.0`.
